POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "email": "alex.j@tes.com",
    "password": "test"
}
###
GET http://localhost:5000/api/auth/current-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDUwYjdiMDUzOGI0NWQ4YmU2NjI4ZiIsImZpcnN0TmFtZSI6IkFsZXgiLCJsYXN0TmFtZSI6IkplbGlzb24iLCJpYXQiOjE3MTE3NzA2NDEsImV4cCI6MTc0MzMyODI0MX0.cD_oD4PFVVSgBb6bg77z0vDEMTZkQgcoJOP3_IYU9O4